global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rate_limiter"
    static_configs:
      - targets: ["ratelimiter1:8081", "ratelimiter2:8082"]
    scrape_interval: 5s

  - job_name: "load_balancer"
    static_configs:
      - targets: ["loadbalancer:8080"]
    scrape_interval: 5s
